name: CI
on:
  push:
    branches: [fe/develop, develop]
  pull_request:
    branches: [fe/develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Use Node 14
        uses: actions/setup-node@1
        with:
          node-version: "14.x"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build --if-present

      - name: Test
        run: npm test
